FROM connectiq as recordingcontrol

ARG SDK_BIN_DIR=/home/user/.Garmin/ConnectIQ/Sdks/connectiq-sdk-lin-3.2.4-2021-01-05-1bf53aeed/bin

ENV PATH=${SDK_BIN_DIR}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# CMD ["/bin/sh"]
ENTRYPOINT eclipse
